name: Tetrasexagesimate 
markdown: redcarpet
pygments: true
github: www.github.com/tetrasexagesimate
about: Things and stuff and TACOS!!!
urls:
    - text: github
      url: https://github.com/tetrasexagesimate
    - text: email
      url: mailto:richardebaker+tetra@gmail.com
